language: php

php:
  - '7.1'
  - '7.2'

install:
  - composer install

script:
  - vendor/bin/phpunit --bootstrap vendor/autoload.php tests

jobs:
  include:
    - stage: build
      services:
        - docker
      install:
        - cp .env.example .env
        - eval "$(ssh-agent -s)"
        - docker-compose up -d
      script:
       - curl localhost:8080
