dist: trusty

services:
  - docker

install:
  - make setup
  - eval "$(ssh-agent -s)"
  - docker-compose up -d

script:
 - docker-compose run php composer install
 - docker-compose exec php bin/behat --config=behat/behat.yml
