version: '3'

## NOTES:
# if you see ${SOME_VAR} in this file,
# these values are taken from .env file

#########################
#          DEV          #
#########################

services:

  nginx:
    build: ./.docker/nginx-php
    restart: "${RESTART_POLICIES}"
    depends_on:
      - php
    ports :
      - "${NGINX_PORT}:80"
    environment:
      - "SERVER_NAME=${SERVER_NAME}"
      - "PHP_ADDRESS=${PHP_ADDRESS}"
      - "TZ=${TIMEZONE}"
    volumes:
      - ./public:/usr/share/nginx/html
    networks:
      - "docker-dev-skeleton"

  php:
    build:
      context: ./.docker/php-fpm/7.1
      args:
        DOCKER_USER: ${DOCKER_USER}
        DOCKER_USER_ID: ${DOCKER_USER_ID}
    restart: "${RESTART_POLICIES}"
    environment:
      TZ: ${TIMEZONE}
      XDEBUG_CONFIG: remote_host=${REMOTE_HOST}
      SSH_AUTH_SOCK: /ssh-agent
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/var/www/html
      - $SSH_AUTH_SOCK:/ssh-agent
    working_dir: /var/www/html
    user: "${DOCKER_USER}"
    entrypoint:
      - ""
    command:
      - "php-fpm"
    networks:
      - "docker-dev-skeleton"

  postgres:
    build:
      context: ./.docker/postgres/9.4
    ports:
      - ${DB_PORT_EXTERNAL}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - "docker-dev-skeleton"

networks:
    docker-dev-skeleton:
        driver: bridge
