version: '3'

## NOTES:
# if you see ${SOME_VAR} in this file,
# these values are taken from .env file

#########################
#          DEV          #
#########################

services:

  nginx:
    build:
      context: $PWD/nginx-php
      dockerfile: Dockerfile
    restart: "${RESTART_POLICIES}"
    ports :
      - "${NGINX_PORT}:80"
    environment:
      - "SERVER_NAME=${SERVER_NAME}"
      - "PHP_ADDRESS=${PHP_ADDRESS}"
      - "TZ=${TIMEZONE}"
    volumes:
      - "$PWD/app/public:/usr/share/nginx/html"
    networks:
      - "docker-dev-skeleton"

  php:
    build:
      context: $PWD/php-fpm/7.1
      dockerfile: Dockerfile
    restart: "${RESTART_POLICIES}"
    environment:
      - "TZ=${TIMEZONE}"
      - "XDEBUG_CONFIG=remote_host=${REMOTE_HOST}"
    volumes:
      - "$PWD/app:/var/www/html"
      - "$PWD/php-fpm/7.1/config/.bashrc:/root/.bashrc"
    networks:
      - "docker-dev-skeleton"


networks:
    docker-dev-skeleton:
        driver: bridge
